x-default-asap-volumes: &default-asap-volumes
  - type: bind
    source: /tmp/.X11-unix
    target: /tmp/.X11-unix
  - type: bind
    source: /etc/localtime
    target: /etc/localtime
    read_only: true
  - type: bind
    source: ../
    target: ${ASAP_PATH}

x-default-asap-environment: &default-asap-environment
  - DISPLAY
  - TERM
  - QT_X11_NO_MITSHM=1
  - XAUTHORITY=${__ISAACLAB_TMP_XAUTH}
  - MESA_GL_VERSION_OVERRIDE

x-default-asap-deploy: &default-asap-deploy
  resources:
    reservations:
      devices:
        - driver: nvidia
          count: all
          capabilities: [ gpu ]

services:
  # This service is the vnc desktop image
  desktop:
    image: ghcr.io/matsuolab/virtual_desktop:latest
    runtime: nvidia
    environment: *default-asap-environment
    ports:
      - "${WEB_PORT}:6080"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    security_opt:
      - seccomp:unconfined
    deploy: *default-asap-deploy
  # This service is the ASAP image
  asap:
    profiles: [ "asap" ]
    env_file: .env
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - ASAP_PATH_ARG=${ASAP_PATH}
        - DOCKER_USER_HOME_ARG=${DOCKER_USER_HOME}
    image: asap:${ASAP_VERSION}
    depends_on:
      - desktop
    environment: *default-asap-environment
    volumes: *default-asap-volumes
    network_mode: host
    deploy: *default-asap-deploy
    # This is the entrypoint for the container
    entrypoint: bash
    stdin_open: true
    tty: true
